<?php

/**
 * @file
 * Contains chatbot.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatbot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chatbot module.
    case 'help.page.chatbot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chatbot Module') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_theme().
 */
function chatbot_theme() {
  return array(
    'block__chatbot_bot_block' => array( 
      'base hook' => 'block'
    ),
  );
}
function chatbot_page_attachments_alter(&$page) {
    $page['#attached']['library'][] = 'chatbot/chatbot.block';
}

